import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new', args:['--no-sandbox']})
const p = await b.newPage()
const errs=[]; p.on('pageerror',e=>errs.push(e.message.slice(0,100))); p.on('console',m=>m.type()==='error'&&errs.push(m.text().slice(0,100)))
await p.setViewport({ width: 1680, height: 1150, deviceScaleFactor: 1 })
// the promotion diff
await p.goto('http://localhost:5177/chapter/g-turn-the-image-digest-into-a-promotion-pull-request',{waitUntil:'domcontentloaded'})
await new Promise(r=>setTimeout(r,3000))
console.log('h1:', await p.evaluate(()=>document.querySelector('h1')?.innerText.replace(/\n/g,' ')))
console.log('tags:', await p.evaluate(()=>[...document.querySelectorAll('article header .type-label')].map(e=>e.innerText).join(' | ')))
await p.evaluate(()=>{const l=[...document.querySelectorAll('article .type-label')].find(e=>e.textContent==='diff'); l?.scrollIntoView({block:'center'})})
await new Promise(r=>setTimeout(r,500))
await p.screenshot({ path:'/tmp/g-diff.png', clip:{x:300,y:300,width:820,height:420} })
// overview: legend + soundings
await p.goto('http://localhost:5177/',{waitUntil:'domcontentloaded'}); await new Promise(r=>setTimeout(r,2800))
console.log('soundings:', await p.evaluate(()=>[...document.querySelectorAll('section dl > div')].slice(0,4).map(x=>x.innerText.replace(/\n/g,' ')).join(' | ')))
console.log('legend   :', await p.evaluate(()=>[...document.querySelectorAll('#method dl > div')].map(x=>x.innerText.replace(/\n/g,' → ')).join('   ')))
console.log('appendices line:', await p.evaluate(()=>[...document.querySelectorAll('#method p')].pop()?.innerText.slice(0,150)))
await p.evaluate(()=>window.scrollTo(0,0)); await new Promise(r=>setTimeout(r,400))
await p.screenshot({ path:'/tmp/g-rail.png', clip:{x:0,y:0,width:310,height:1150} })
console.log('ERRORS:', errs.length?errs:'none')
await b.close()
